apiVersion: v1
kind: Namespace
metadata:
  name: ambient-test
  labels:
    istio.io/dataplane-mode: ambient
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sleep
  namespace: ambient-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sleep
  template:
    metadata:
      labels:
        app: sleep
        istio.io/dataplane-mode: ambient
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: sleep
        image: nginx
        command: ["/bin/sleep", "3650d"]
        imagePullPolicy: IfNotPresent
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: ambient-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        istio.io/dataplane-mode: ambient
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: nginx
        image: nginx
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: ambient-test
spec:
  selector:
    app: nginx
  ports:
  - name: http
    port: 80
    targetPort: 80